name: CI/CD Pipeline with Performance Test

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run the application (in the background)
      run: |
        nohup node index.js > app.log 2>&1 & 
        echo "Node.js application started in the background"

    - name: Install K6
      run: |
        curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6

    - name: Run K6 load test
      run: k6 run loadTest.js

    - name: Debug Node.js process
      run: |
        # List all running Node.js processes
        ps aux | grep node
        cat app.log  # Output the logs of the application to check for errors

    - name: Stop the application
      run: |
        # Find the Node.js process by its port (assuming it's running on port 3000)
        pid=$(ps aux | grep 'node index.js' | grep -v grep | awk '{print $2}')
        if [ -n "$pid" ]; then
          echo "Stopping Node.js process with PID: $pid"
          kill $pid
        else
          echo "Node.js process not found"
        fi